# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import browser_service_pb2 as browser__service__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in browser_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrowserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartBrowser = channel.unary_unary(
                '/browser.BrowserService/StartBrowser',
                request_serializer=browser__service__pb2.Empty.SerializeToString,
                response_deserializer=browser__service__pb2.Response.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/browser.BrowserService/ExecuteCommand',
                request_serializer=browser__service__pb2.Command.SerializeToString,
                response_deserializer=browser__service__pb2.Response.FromString,
                _registered_method=True)
        self.ShutdownBrowser = channel.unary_unary(
                '/browser.BrowserService/ShutdownBrowser',
                request_serializer=browser__service__pb2.Empty.SerializeToString,
                response_deserializer=browser__service__pb2.Response.FromString,
                _registered_method=True)


class BrowserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartBrowser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShutdownBrowser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrowserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartBrowser': grpc.unary_unary_rpc_method_handler(
                    servicer.StartBrowser,
                    request_deserializer=browser__service__pb2.Empty.FromString,
                    response_serializer=browser__service__pb2.Response.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=browser__service__pb2.Command.FromString,
                    response_serializer=browser__service__pb2.Response.SerializeToString,
            ),
            'ShutdownBrowser': grpc.unary_unary_rpc_method_handler(
                    servicer.ShutdownBrowser,
                    request_deserializer=browser__service__pb2.Empty.FromString,
                    response_serializer=browser__service__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'browser.BrowserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('browser.BrowserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrowserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartBrowser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser.BrowserService/StartBrowser',
            browser__service__pb2.Empty.SerializeToString,
            browser__service__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser.BrowserService/ExecuteCommand',
            browser__service__pb2.Command.SerializeToString,
            browser__service__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShutdownBrowser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser.BrowserService/ShutdownBrowser',
            browser__service__pb2.Empty.SerializeToString,
            browser__service__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
